// GENERATED by scripts/fetch-films.mjs — do not edit by hand.
// Poster paths point at TMDB's CDN; no poster art is stored in this repository.
// TMDB's terms require the attribution rendered in components/Footer.tsx.

export type Film = {
  tmdbId: number;
  title: string;
  year: string;
  character: string;
  posterPath: string | null;
  backdropPath: string | null;
  overview: string;
};

/** TMDB image CDN. Widths must be ones TMDB actually serves. */
export const tmdbImage = (path: string, width: "w342" | "w500" | "w780" | "original") =>
  `https://image.tmdb.org/t/p/${width}${path}`;

export const films: Film[] = [
  {
    "tmdbId": 168245,
    "title": "Kai Po Che!",
    "year": "2013",
    "character": "Ishaan Bhatt",
    "posterPath": "/cAlv5vmDXzpVmTCk4DmggUbW7cd.jpg",
    "backdropPath": "/uvtQQMCMR50e8Ahs6RRpOrAYk1Y.jpg",
    "overview": "Three friends growing up in India at the turn of the millennium set out to open a training academy to produce the country's next cricket stars."
  },
  {
    "tmdbId": 209410,
    "title": "Shuddh Desi Romance",
    "year": "2013",
    "character": "Raghu Ram Sitaram",
    "posterPath": "/j141I2N8e8HuVHEDNPZ1K2qeqM4.jpg",
    "backdropPath": "/pliGfHo50O6JOnZBgkIQqrMmPVC.jpg",
    "overview": "A journey of three restless young people who junk the society's syllabus for finding love and decide to follow their heart."
  },
  {
    "tmdbId": 297222,
    "title": "PK",
    "year": "2014",
    "character": "Sarfaraz Yousuf",
    "posterPath": "/z2x2Y4tncefsIU7h82gmUM5vnBJ.jpg",
    "backdropPath": "/gxfvtq5eYiClS2X7hxAAPBNrbWA.jpg",
    "overview": "A stranger in the city asks questions no one has asked before. Known only by his initials, the man's innocent questions and childlike curiosity take him on a journey of love, laughter and letting go."
  },
  {
    "tmdbId": 320295,
    "title": "Detective Byomkesh Bakshy!",
    "year": "2015",
    "character": "Byomkesh Bakshy",
    "posterPath": "/7IvuZioWIvj8UAIWJhGtLsqwwt.jpg",
    "backdropPath": "/hjHz3Nttria4DglKilLiVjS3exz.jpg",
    "overview": "Byomkesh, fresh out of college, agrees to investigate the disappearance of Bhuvan, a chemist. Assisted by Bhuvan's son Ajit, Byomkesh links the case to a larger conspiracy that will unsettle Calcutta."
  },
  {
    "tmdbId": 388333,
    "title": "M.S. Dhoni: The Untold Story",
    "year": "2016",
    "character": "Mahendra Singh Dhoni",
    "posterPath": "/lUpMckVHaB55YJ3SMK0arwxKmCt.jpg",
    "backdropPath": "/oQCrHuAqqQCJ5H2gvAbsXd0T4Sw.jpg",
    "overview": "Based on the life story of Mahendra Singh Dhoni, and his journey to being the world cup winning captain of the Indian cricket team."
  },
  {
    "tmdbId": 456562,
    "title": "Raabta",
    "year": "2017",
    "character": "Shiv / Jilaan",
    "posterPath": "/ovdpOhdgYqhDmy3uYGhNN16CKzQ.jpg",
    "backdropPath": "/yfsDFQq9RN28aYfxM3MuVQ21AcO.jpg",
    "overview": "An inseparable couple Saira and Shiva find themselves in a complicated situation when a stranger claims to be her reincarnated lover from their previous lifetime, hellbent on destroying their relationship and winning her back."
  },
  {
    "tmdbId": 465656,
    "title": "Kedarnath",
    "year": "2018",
    "character": "Mansoor Khan",
    "posterPath": "/viq6ltqew6ZU6dur1FUVKpf9tiZ.jpg",
    "backdropPath": "/rxAOiBCivJNzL0rXcrlyreofZb0.jpg",
    "overview": "Mansoor, a reserved and reticent Pithoo (porter), helps pilgrims make an arduous journey upwards to the temple town. His world turns around when he meets the beautiful and rebellious Mukku who draws him into a whirlwind of intense love."
  },
  {
    "tmdbId": 535144,
    "title": "Sonchiriya",
    "year": "2019",
    "character": "Lakhna",
    "posterPath": "/7ygikeDbneOlUFIQyvAmMrvi3vJ.jpg",
    "backdropPath": "/fVxbEDd7ci0TE4ljsK13oyNUeW7.jpg",
    "overview": "A legion of warring bandits terrorizes India's Chambal Valley."
  },
  {
    "tmdbId": 596650,
    "title": "Chhichhore",
    "year": "2019",
    "character": "Anirudh Pathak",
    "posterPath": "/cGDPQtQ5igtPMt3oJ6BCAor6dFp.jpg",
    "backdropPath": "/32RgjX5oniUvL9UpU8TiYlmaydC.jpg",
    "overview": "Following a group of friends from university as they progress into middle-age life and go their own separate ways."
  },
  {
    "tmdbId": 466550,
    "title": "Drive",
    "year": "2019",
    "character": "Samar",
    "posterPath": "/1ZUNyvVGTPkeBVXXTMnhIRoXlfo.jpg",
    "backdropPath": "/21bk7sqIsFfeof4vppwGEw1Ahvw.jpg",
    "overview": "A notorious thief allies with a street racer for a grand heist involving an elaborate game of deceit with authorities, who have their own dirty secrets."
  },
  {
    "tmdbId": 645484,
    "title": "Dil Bechara",
    "year": "2020",
    "character": "Immanuel Rajkumar Junior",
    "posterPath": "/lMFjMrc8Bn0CQhtJDORfspXrWrK.jpg",
    "backdropPath": "/tnwoGCRe2GV05f1RSIl1PusYc9v.jpg",
    "overview": "Kizie and Manny, two ordinary people brought together by a tragic twist, embark on a bittersweet and extraordinary journey into the heart of that crazy little thing called 'life'."
  }
];
