// GENERATED by scripts/fetch-songs.mjs — do not edit by hand.
// Every id was resolved from an official label channel and then confirmed
// through YouTube's oEmbed endpoint. Tracks without a verified official
// upload are omitted rather than guessed.

export type Song = {
  title: string;
  film: string;
  year: string;
  youtubeId: string;
  /** The channel that owns the upload, shown beside the track. */
  source: string;
  singers: string;
};

export const songs: Song[] = [
  {
    "title": "Manjha",
    "film": "Kai Po Che!",
    "year": "2013",
    "youtubeId": "YKcmMmJlKNk",
    "source": "SonyMusicIndiaVEVO",
    "singers": "Amit Trivedi, Mohan Kannan"
  },
  {
    "title": "Shubhaarambh",
    "film": "Kai Po Che!",
    "year": "2013",
    "youtubeId": "Gx_Rqsq1DIw",
    "source": "Sony Music India",
    "singers": "Shruti Pathak, Divya Kumar"
  },
  {
    "title": "Meethi Boliyaan",
    "film": "Kai Po Che!",
    "year": "2013",
    "youtubeId": "BO9cos32DYc",
    "source": "SonyMusicIndiaVEVO",
    "singers": "Amit Trivedi, Mili Nair"
  },
  {
    "title": "Tere Mere Beech Mein",
    "film": "Shuddh Desi Romance",
    "year": "2013",
    "youtubeId": "3t0dsPbruok",
    "source": "YRF",
    "singers": "Sunidhi Chauhan, Mohit Chauhan"
  },
  {
    "title": "Gulabi",
    "film": "Shuddh Desi Romance",
    "year": "2013",
    "youtubeId": "E4ZJxhyAaH8",
    "source": "YRF",
    "singers": "Jigar Saraiya, Priya Saraiya"
  },
  {
    "title": "Chanchal Mann Ati Random",
    "film": "Shuddh Desi Romance",
    "year": "2013",
    "youtubeId": "CdWe8J-m_Ug",
    "source": "YRF",
    "singers": "Divya Kumar"
  },
  {
    "title": "Shuddh Desi Romance",
    "film": "Shuddh Desi Romance",
    "year": "2013",
    "youtubeId": "varo0G9I-gk",
    "source": "YRF",
    "singers": "Benny Dayal, Shalmali Kholgade"
  },
  {
    "title": "Tharki Chokro",
    "film": "PK",
    "year": "2014",
    "youtubeId": "nd4wsdUMorY",
    "source": "T-Series",
    "singers": "Swaroop Khan"
  },
  {
    "title": "Love Is a Waste of Time",
    "film": "PK",
    "year": "2014",
    "youtubeId": "jAmzBv3oq8M",
    "source": "T-Series",
    "singers": "Sonu Nigam, Shreya Ghoshal"
  },
  {
    "title": "Nanga Punga Dost",
    "film": "PK",
    "year": "2014",
    "youtubeId": "m2a3WlRyWGM",
    "source": "T-Series",
    "singers": "Shreya Ghoshal"
  },
  {
    "title": "Chaar Kadam",
    "film": "PK",
    "year": "2014",
    "youtubeId": "WKbwopSXLWU",
    "source": "T-Series",
    "singers": "Shaan, Shreya Ghoshal"
  },
  {
    "title": "Bhagwan Hai Kahan Re Tu",
    "film": "PK",
    "year": "2014",
    "youtubeId": "G6SutyLlzws",
    "source": "T-Series",
    "singers": "Sonu Nigam"
  },
  {
    "title": "Dil Darbadar",
    "film": "PK",
    "year": "2014",
    "youtubeId": "f3KYlEYq3IM",
    "source": "T-Series",
    "singers": "Ankit Tiwari"
  },
  {
    "title": "Khuda",
    "film": "PK",
    "year": "2014",
    "youtubeId": "IgK5-PUeARg",
    "source": "T-Series",
    "singers": "Hareem Farooq and Shiraz Uppal"
  },
  {
    "title": "Calcutta Kiss",
    "film": "Detective Byomkesh Bakshy!",
    "year": "2015",
    "youtubeId": "AXi2nYjkD04",
    "source": "YRF",
    "singers": "Imaad Shah, Saba Azad"
  },
  {
    "title": "Bach Ke Bakshy",
    "film": "Detective Byomkesh Bakshy!",
    "year": "2015",
    "youtubeId": "bjKQzuAaGOM",
    "source": "YRF",
    "singers": "Gowri Jayakumar, Big Deal, Thomson Andrews, Trevor Furtado, Rap by: Smokey the Ghost, Craz Professa"
  },
  {
    "title": "Jaanam",
    "film": "Detective Byomkesh Bakshy!",
    "year": "2015",
    "youtubeId": "pwfw3yPqjGs",
    "source": "Saregama Music",
    "singers": "Suryakant Sawhney"
  },
  {
    "title": "Padhoge Likhoge",
    "film": "M.S. Dhoni: The Untold Story",
    "year": "2016",
    "youtubeId": "Yq6mzcWR0PE",
    "source": "T-Series",
    "singers": "Aparnaa Bhaagwat, Adithyan A. Prithviraj"
  },
  {
    "title": "Jab Tak",
    "film": "M.S. Dhoni: The Untold Story",
    "year": "2016",
    "youtubeId": "K-Ts-NFR62o",
    "source": "T-Series",
    "singers": "Sangeet Haldipur"
  },
  {
    "title": "Parwah Nahin",
    "film": "M.S. Dhoni: The Untold Story",
    "year": "2016",
    "youtubeId": "GWsd3SMNvto",
    "source": "T-Series",
    "singers": "| title4 = Dhundicha Kshan Ha Ola"
  },
  {
    "title": "Phir Kabhi",
    "film": "M.S. Dhoni: The Untold Story",
    "year": "2016",
    "youtubeId": "qVHaXD7zHDQ",
    "source": "T-Series",
    "singers": "Reprise"
  },
  {
    "title": "Kaun Tujhe",
    "film": "M.S. Dhoni: The Untold Story",
    "year": "2016",
    "youtubeId": "atVof3pjT-I",
    "source": "T-Series",
    "singers": "Armaan Malik Version"
  },
  {
    "title": "Har Gully Mein Dhoni Hai",
    "film": "M.S. Dhoni: The Untold Story",
    "year": "2016",
    "youtubeId": "EwE8wH9g95w",
    "source": "T-Series",
    "singers": "S. P. B. Charan"
  },
  {
    "title": "Besabriyaan",
    "film": "M.S. Dhoni: The Untold Story",
    "year": "2016",
    "youtubeId": "UBBHpoW3AKA",
    "source": "T-Series",
    "singers": "Sangeet Haldipur"
  },
  {
    "title": "Ik Vaari Aa",
    "film": "Raabta",
    "year": "2017",
    "youtubeId": "zXLgYBSdv74",
    "source": "T-Series",
    "singers": "Arijit Singh"
  },
  {
    "title": "Raabta",
    "film": "Raabta",
    "year": "2017",
    "youtubeId": "zlt38OOqwDc",
    "source": "T-Series",
    "singers": "Arijit Singh, Nikhita Gandhi"
  },
  {
    "title": "Sadda Move",
    "film": "Raabta",
    "year": "2017",
    "youtubeId": "Xf0sFq5IdCI",
    "source": "T-Series",
    "singers": "Diljit Dosanjh, Pardeep Singh Sran, Raftaar"
  },
  {
    "title": "Lambiyaan Si Judaiyaan",
    "film": "Raabta",
    "year": "2017",
    "youtubeId": "Z1wN6_mCYbw",
    "source": "T-Series",
    "singers": "Arijit Singh, Shadaab Faridi, Altamash Faridi"
  },
  {
    "title": "Main Tera Boyfriend",
    "film": "Raabta",
    "year": "2017",
    "youtubeId": "FQS7i2z1CoA",
    "source": "T-Series",
    "singers": "Arijit Singh, Neha Kakkar, Meet Bros"
  },
  {
    "title": "Darasal",
    "film": "Raabta",
    "year": "2017",
    "youtubeId": "uCMYzolEbO0",
    "source": "T-Series",
    "singers": "Atif Aslam"
  },
  {
    "title": "Namo Namo",
    "film": "Kedarnath",
    "year": "2018",
    "youtubeId": "HFX6AZ5bDDo",
    "source": "Zee Music Company",
    "singers": "Amit Trivedi"
  },
  {
    "title": "Sweetheart",
    "film": "Kedarnath",
    "year": "2018",
    "youtubeId": "58r8MDf5sxQ",
    "source": "Zee Music Company",
    "singers": "Dev Negi"
  },
  {
    "title": "Qaafirana",
    "film": "Kedarnath",
    "year": "2018",
    "youtubeId": "ZmcBC9-wAXM",
    "source": "Zee Music Company",
    "singers": "Arijit Singh, Nikhita Gandhi"
  },
  {
    "title": "Jaan 'Nisaar",
    "film": "Kedarnath",
    "year": "2018",
    "youtubeId": "za4Q_7gYyS4",
    "source": "Zee Music Company",
    "singers": "Arijit Singh"
  },
  {
    "title": "Baaghi Re",
    "film": "Sonchiriya",
    "year": "2019",
    "youtubeId": "CN-8rtdkJaM",
    "source": "Zee Music Company",
    "singers": "Mame Khan"
  },
  {
    "title": "Sonchiraiya",
    "film": "Sonchiriya",
    "year": "2019",
    "youtubeId": "um8kaiGa7m0",
    "source": "Zee Music Company",
    "singers": "Rekha Bhardwaj"
  },
  {
    "title": "Ruan Ruan",
    "film": "Sonchiriya",
    "year": "2019",
    "youtubeId": "S6SLveEIMOA",
    "source": "Zee Music Company",
    "singers": "Arijit Singh"
  },
  {
    "title": "Naina Na Maar",
    "film": "Sonchiriya",
    "year": "2019",
    "youtubeId": "CEXqKDgioDI",
    "source": "Zee Music Company",
    "singers": "Sukhwinder Singh, Rekha Bhardwaj"
  },
  {
    "title": "Saanp Khavega",
    "film": "Sonchiriya",
    "year": "2019",
    "youtubeId": "ECzKQWHIZ78",
    "source": "Zee Music Company",
    "singers": "Sukhwinder Singh"
  },
  {
    "title": "Woh Din",
    "film": "Chhichhore",
    "year": "2019",
    "youtubeId": "xC1cj9zhh6k",
    "source": "T-Series",
    "singers": "Film Version"
  },
  {
    "title": "Control",
    "film": "Chhichhore",
    "year": "2019",
    "youtubeId": "ABG0gQ9czvk",
    "source": "T-Series",
    "singers": "Nakash Aziz, Manish J. Tipu, Geet Sagar, Sreerama Chandra, Amitabh Bhattacharya"
  },
  {
    "title": "Fikar Not",
    "film": "Chhichhore",
    "year": "2019",
    "youtubeId": "mxva6l4bCSI",
    "source": "T-Series",
    "singers": "Nakash Aziz, Dev Negi, Antara Mitra, Amit Mishra, Sreerama Chandra, Amitabh Bhattacharya"
  },
  {
    "title": "Kal Ki Hi Baat Hai",
    "film": "Chhichhore",
    "year": "2019",
    "youtubeId": "JeGBNhyJeE4",
    "source": "T-Series",
    "singers": "KK"
  },
  {
    "title": "Khairiyat",
    "film": "Chhichhore",
    "year": "2019",
    "youtubeId": "hoNb6HuNmU0",
    "source": "T-Series",
    "singers": "Arijit Singh"
  },
  {
    "title": "Karma",
    "film": "Drive",
    "year": "2019",
    "youtubeId": "QDyL8YQpzoQ",
    "source": "Zee Music Company",
    "singers": "Sukriti Kakar"
  },
  {
    "title": "Makhna",
    "film": "Drive",
    "year": "2019",
    "youtubeId": "HqUeSjsYLNU",
    "source": "Zee Music Company",
    "singers": "Yasser Desai, Asees Kaur"
  },
  {
    "title": "Prem Pujari",
    "film": "Drive",
    "year": "2019",
    "youtubeId": "r3ytGXNHy4A",
    "source": "Zee Music Company",
    "singers": "Amit Mishra, Akasa Singh, Amartya Bobo Rahut, Dev Arijit"
  },
  {
    "title": "Black Car",
    "film": "Drive",
    "year": "2019",
    "youtubeId": "X7n3ddvmT98",
    "source": "Zee Music Company",
    "singers": "Suraj Chauhan, Shivi, Ariff Khan"
  },
  {
    "title": "Tu Jaanta Nahi",
    "film": "Drive",
    "year": "2019",
    "youtubeId": "PNkAMNa-mI0",
    "source": "Zee Music Company",
    "singers": "Javed-Mohsin, Parry G, Ceazer"
  },
  {
    "title": "Dil Bechara",
    "film": "Dil Bechara",
    "year": "2020",
    "youtubeId": "PMCu0JtizCk",
    "source": "Sony Music India",
    "singers": "A. R. Ameen"
  },
  {
    "title": "Taare Ginn",
    "film": "Dil Bechara",
    "year": "2020",
    "youtubeId": "HhWum37Mg8o",
    "source": "SonyMusicIndiaVEVO",
    "singers": "Mohit Chauhan, Shreya Ghoshal"
  },
  {
    "title": "Khulke Jeene Ka",
    "film": "Dil Bechara",
    "year": "2020",
    "youtubeId": "PzmNssVLcLQ",
    "source": "Sony Music India",
    "singers": "Arijit Singh, Shashaa Tirupati"
  },
  {
    "title": "Main Tumhara",
    "film": "Dil Bechara",
    "year": "2020",
    "youtubeId": "8Q5d0P6x61k",
    "source": "Sony Music India",
    "singers": "Jonita Gandhi, Hriday Gattani"
  },
  {
    "title": "Maskhari",
    "film": "Dil Bechara",
    "year": "2020",
    "youtubeId": "8f6EPOKn6zg",
    "source": "Sony Music India",
    "singers": "Sunidhi Chauhan, Hriday Gattani"
  },
  {
    "title": "Afreeda",
    "film": "Dil Bechara",
    "year": "2020",
    "youtubeId": "SxcKpclnYUI",
    "source": "SonyMusicIndiaVEVO",
    "singers": "Sanaa Moussa, Raja Kumari"
  },
  {
    "title": "Never Say Goodbye",
    "film": "Dil Bechara",
    "year": "2020",
    "youtubeId": "ftJODeE_qg8",
    "source": "Sony Music India",
    "singers": "A. R. Ameen"
  }
];

/** YouTube's own thumbnail for a video; hotlinked, never re-hosted. */
export const songArtwork = (id: string) => `https://img.youtube.com/vi/${id}/hqdefault.jpg`;

/** Track lists grouped by film, in release order. */
export const songsByFilm = songs.reduce<Record<string, Song[]>>((acc, s) => {
  (acc[s.film] ??= []).push(s);
  return acc;
}, {});
