/**
 * Resolves the filmography and writes data/films.ts.
 *
 * Poster art is copyrighted, so nothing is downloaded — the generated file
 * stores TMDB CDN paths which <Image> loads at runtime (see the remotePattern
 * in next.config.ts). The credential is read from .env.local and never reaches
 * the client bundle.
 *
 * IMDb ids come from Wikidata rather than TMDB: they are the same ids, and
 * api.themoviedb.org is intermittently blocked by some Indian ISPs, so the
 * fewer calls that endpoint has to serve, the better.
 *
 * Re-run with:  pnpm films
 */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

const PERSON_ID = 1192902; // Sushant Singh Rajput
const API = "https://api.themoviedb.org/3";
const TOKEN = process.env.TMDB_READ_TOKEN;
const UA = "SSRUniverse/0.1 (fan memorial; mrityunjay.kumar@appknit.io)";

/**
 * The curated canon, in release order. TMDB supplies the artwork; this list
 * decides which credits belong on the site and how the roles are named, so a
 * cameo (Welcome to New York) or a TMDB rename cannot quietly change the page.
 * `wiki` is the English Wikipedia article, used to reach the Wikidata item.
 */
const CANON = [
  { match: "Kai Po Che!", character: "Ishaan Bhatt", wiki: "Kai Po Che!" },
  { match: "Shuddh Desi Romance", character: "Raghu Ram Sitaram", wiki: "Shuddh Desi Romance" },
  { match: "PK", character: "Sarfaraz Yousuf", wiki: "PK (film)" },
  { match: "Detective Byomkesh Bakshy!", character: "Byomkesh Bakshy", wiki: "Detective Byomkesh Bakshy!" },
  { match: "M.S. Dhoni: The Untold Story", character: "Mahendra Singh Dhoni", wiki: "M.S. Dhoni: The Untold Story" },
  { match: "Raabta", character: "Shiv / Jilaan", wiki: "Raabta (film)" },
  { match: "Kedarnath", character: "Mansoor Khan", wiki: "Kedarnath (film)" },
  { match: "Sonchiriya", character: "Lakhna", wiki: "Sonchiriya" },
  { match: "Chhichhore", character: "Anirudh Pathak", wiki: "Chhichhore" },
  { match: "Drive", character: "Samar", wiki: "Drive (2019 film)" },
  { match: "Dil Bechara", character: "Immanuel Rajkumar Junior", wiki: "Dil Bechara" },
];

/** The API is intermittently unreachable on some ISPs; retry before failing. */
async function api(path, attempts = 4) {
  let lastError;
  for (let i = 1; i <= attempts; i++) {
    try {
      const res = await fetch(`${API}${path}`, {
        headers: { Authorization: `Bearer ${TOKEN}`, accept: "application/json" },
        signal: AbortSignal.timeout(20_000),
      });
      if (!res.ok) throw new Error(`TMDB ${res.status} for ${path}`);
      return res.json();
    } catch (err) {
      lastError = err;
      if (i < attempts) console.log(`  … retry ${i}/${attempts - 1} (${err.message})`);
    }
  }
  throw lastError;
}

/** Wikipedia article titles -> IMDb ids, via each article's Wikidata item. */
export async function imdbIds(articles) {
  const wiki = await fetch(
    `https://en.wikipedia.org/w/api.php?${new URLSearchParams({
      action: "query", prop: "pageprops", ppprop: "wikibase_item",
      titles: articles.join("|"), format: "json", formatversion: "2",
    })}`,
    { headers: { "User-Agent": UA } },
  ).then((r) => r.json());

  const itemByTitle = new Map(
    wiki.query.pages.map((p) => [p.title, p.pageprops?.wikibase_item]),
  );
  const items = [...itemByTitle.values()].filter(Boolean);

  const data = await fetch(
    `https://www.wikidata.org/w/api.php?${new URLSearchParams({
      action: "wbgetentities", ids: items.join("|"), props: "claims", format: "json",
    })}`,
    { headers: { "User-Agent": UA } },
  ).then((r) => r.json());

  const out = new Map();
  for (const [title, item] of itemByTitle) {
    // P345 is the IMDb identifier.
    const claim = item && data.entities?.[item]?.claims?.P345?.[0];
    out.set(title, claim ? claim.mainsnak.datavalue.value : null);
  }
  return out;
}

const banner = `// GENERATED by scripts/fetch-films.mjs — do not edit by hand.
// Poster paths point at TMDB's CDN; no poster art is stored in this repository.
// TMDB's terms require the attribution rendered in components/Footer.tsx.
`;

async function main() {
  if (!TOKEN) throw new Error("TMDB_READ_TOKEN missing — is .env.local present?");

  console.log("Resolving filmography against TMDB…");
  const { cast } = await api(`/person/${PERSON_ID}/movie_credits`);

  console.log("Looking up IMDb ids via Wikidata…");
  const imdb = await imdbIds(CANON.map((c) => c.wiki));

  const films = CANON.map(({ match, character, wiki }) => {
    const credit = cast.find((c) => c.title === match);
    if (!credit) throw new Error(`No TMDB credit found for "${match}"`);
    const year = (credit.release_date ?? "").slice(0, 4);
    const imdbId = imdb.get(wiki) ?? null;
    console.log(`  ✓ ${year}  ${credit.title.padEnd(30)} ${imdbId ?? "(no imdb id)"}`);
    return {
      tmdbId: credit.id,
      imdbId,
      title: credit.title,
      year,
      character,
      posterPath: credit.poster_path,
      backdropPath: credit.backdrop_path,
      overview: credit.overview ?? "",
    };
  });

  await writeFile(
    join(process.cwd(), "data", "films.ts"),
    `${banner}
export type Film = {
  tmdbId: number;
  imdbId: string | null;
  title: string;
  year: string;
  character: string;
  posterPath: string | null;
  backdropPath: string | null;
  overview: string;
};

/** Where a film card sends you: IMDb when known, TMDB otherwise. */
export const filmLink = (film: Film) =>
  film.imdbId
    ? \`https://www.imdb.com/title/\${film.imdbId}/\`
    : \`https://www.themoviedb.org/movie/\${film.tmdbId}\`;

/** TMDB image CDN. Widths must be ones TMDB actually serves. */
export const tmdbImage = (path: string, width: "w342" | "w500" | "w780" | "original") =>
  \`https://image.tmdb.org/t/p/\${width}\${path}\`;

export const films: Film[] = ${JSON.stringify(films, null, 2)};
`,
  );

  console.log(`\nWrote data/films.ts (${films.length} films).`);
}

// Allow the helper to be imported without running the whole fetch.
if (import.meta.url === `file://${process.argv[1].replace(/\\/g, "/")}`) {
  main().catch((err) => {
    console.error(`\nFailed: ${err.message}`);
    process.exit(1);
  });
}
