/**
 * Resolves the filmography against TMDB and writes data/films.ts.
 *
 * Poster art is copyrighted, so nothing is downloaded — the generated file
 * stores TMDB CDN paths which <Image> loads at runtime (see the remotePattern
 * in next.config.ts). The credential is read from .env.local and never reaches
 * the client bundle.
 *
 * Re-run with:  pnpm films
 */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

const PERSON_ID = 1192902; // Sushant Singh Rajput
const API = "https://api.themoviedb.org/3";
const TOKEN = process.env.TMDB_READ_TOKEN;

/**
 * The curated canon, in release order. TMDB supplies the artwork; this list
 * decides which credits belong on the site and how the roles are named, so a
 * cameo (Welcome to New York) or a TMDB rename cannot quietly change the page.
 */
const CANON = [
  { match: "Kai Po Che!", character: "Ishaan Bhatt" },
  { match: "Shuddh Desi Romance", character: "Raghu Ram Sitaram" },
  { match: "PK", character: "Sarfaraz Yousuf" },
  { match: "Detective Byomkesh Bakshy!", character: "Byomkesh Bakshy" },
  { match: "M.S. Dhoni: The Untold Story", character: "Mahendra Singh Dhoni" },
  { match: "Raabta", character: "Shiv / Jilaan" },
  { match: "Kedarnath", character: "Mansoor Khan" },
  { match: "Sonchiriya", character: "Lakhna" },
  { match: "Chhichhore", character: "Anirudh Pathak" },
  { match: "Drive", character: "Samar" },
  { match: "Dil Bechara", character: "Immanuel Rajkumar Junior" },
];

/** The API is intermittently unreachable on some ISPs; retry before failing. */
async function api(path, attempts = 4) {
  let lastError;
  for (let i = 1; i <= attempts; i++) {
    try {
      const res = await fetch(`${API}${path}`, {
        headers: { Authorization: `Bearer ${TOKEN}`, accept: "application/json" },
        signal: AbortSignal.timeout(20_000),
      });
      if (!res.ok) throw new Error(`TMDB ${res.status} for ${path}`);
      return res.json();
    } catch (err) {
      lastError = err;
      if (i < attempts) console.log(`  … retry ${i}/${attempts - 1} (${err.message})`);
    }
  }
  throw lastError;
}

const banner = `// GENERATED by scripts/fetch-films.mjs — do not edit by hand.
// Poster paths point at TMDB's CDN; no poster art is stored in this repository.
// TMDB's terms require the attribution rendered in components/Footer.tsx.
`;

async function main() {
  if (!TOKEN) throw new Error("TMDB_READ_TOKEN missing — is .env.local present?");

  console.log("Resolving filmography against TMDB…");
  const { cast } = await api(`/person/${PERSON_ID}/movie_credits`);

  const films = CANON.map(({ match, character }) => {
    const credit = cast.find((c) => c.title === match);
    if (!credit) throw new Error(`No TMDB credit found for "${match}"`);
    const year = (credit.release_date ?? "").slice(0, 4);
    console.log(`  ✓ ${year}  ${credit.title}`);
    return {
      tmdbId: credit.id,
      title: credit.title,
      year,
      character,
      posterPath: credit.poster_path,
      backdropPath: credit.backdrop_path,
      overview: credit.overview ?? "",
    };
  });

  await writeFile(
    join(process.cwd(), "data", "films.ts"),
    `${banner}
export type Film = {
  tmdbId: number;
  title: string;
  year: string;
  character: string;
  posterPath: string | null;
  backdropPath: string | null;
  overview: string;
};

/** TMDB image CDN. Widths must be ones TMDB actually serves. */
export const tmdbImage = (path: string, width: "w342" | "w500" | "w780" | "original") =>
  \`https://image.tmdb.org/t/p/\${width}\${path}\`;

export const films: Film[] = ${JSON.stringify(films, null, 2)};
`,
  );

  console.log(`\nWrote data/films.ts (${films.length} films).`);
}

main().catch((err) => {
  console.error(`\nFailed: ${err.message}`);
  process.exit(1);
});
